[package]
name = "pdfmcr"
version = "0.1.0"
edition = "2024"

[dependencies]
askama = { version = "0.13" }
from-to-repr = { version = "0.2", features = ["from_to_other"] }
rocket = { version = "0.5" }
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.44" }
