packageExtensions:
  "@parcel/node-resolver-core@*":
    dependencies:
      "@parcel/core": '*'
  "@parcel/types@*":
    dependencies:
      "@parcel/core": '*'
  "@parcel/fs@*":
    dependencies:
      "@parcel/core": '*'
